# Generated by Django 2.0.4 on 2018-04-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Light_Number', models.IntegerField(null=True)),
                ('Location', models.TextField(null=True)),
                ('Phone_Number', models.BigIntegerField(null=True)),
                ('reason', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Light_Id', models.CharField(max_length=30)),
                ('Location', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='Lt_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lights'),
        ),
    ]
