# Generated by Django 2.0.4 on 2018-04-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='Light_Number',
        ),
    ]
